services:
  roadblock-services-web:
    image: node:lts
    container_name: roadblock-web
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    command: yarn workspace @zthun/roadblock-web debug